//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highscores
    {
        public int ID { get; set; }
        public int Clicks { get; set; }
        public string Name { get; set; }
        public string Machine { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
